### ISSUE TITLE
TypeError: An asyncio.Future, a coroutine or an awaitable is required

### ISSUE THREAD

**Issue by elgalu** [ideonate/cdsdashboards#8]
Hi, any ideas how to troubleshoot this error? 

```
[E 2020-06-22 15:25:25.045 JupyterHub web:1792] Uncaught exception GET /hub/dashboards-api/rshiny-test/progress (::ffff:10.2.44.0)
    HTTPServerRequest(protocol='http', host='staging-*****', method='GET', uri='/hub/dashboards-api/rshiny-test/progress', version='HTTP/1.1', remote_ip='::ffff:10.2.44.0')
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.7/site-packages/tornado/web.py", line 1703, in _execute
        result = await result
      File "/opt/conda/lib/python3.7/site-packages/cdsdashboards/hubextension/events.py", line 82, in get
        async for event in events:
      File "/opt/conda/lib/python3.7/site-packages/async_generator/_impl.py", line 366, in step
        return await ANextIter(self._it, start_fn, *args)
      File "/opt/conda/lib/python3.7/site-packages/async_generator/_impl.py", line 197, in __next__
        return self._invoke(first_fn, *first_args)
      File "/opt/conda/lib/python3.7/site-packages/async_generator/_impl.py", line 209, in _invoke
        result = fn(*args)
      File "/opt/conda/lib/python3.7/site-packages/jupyterhub/utils.py", line 551, in iterate_until
        [item_future, deadline_future], return_when=asyncio.FIRST_COMPLETED
      File "/opt/conda/lib/python3.7/asyncio/tasks.py", line 387, in wait
        fs = {ensure_future(f, loop=loop) for f in set(fs)}
      File "/opt/conda/lib/python3.7/asyncio/tasks.py", line 387, in <setcomp>
        fs = {ensure_future(f, loop=loop) for f in set(fs)}
      File "/opt/conda/lib/python3.7/asyncio/tasks.py", line 619, in ensure_future
        raise TypeError('An asyncio.Future, a coroutine or an awaitable is '
    TypeError: An asyncio.Future, a coroutine or an awaitable is required
```

**Comment by danlester** [comment]
Thank you for this report. I have spoken to you about this privately already, but for anyone else who encounters something similar:

If this happened every time the dashboard attempts to start, there might be something deeper in your configuration that we need to investigate. If it only happened occasionally, especially on a high traffic JupyterHub, it was most likely a race condition that is fixed in the latest code and will be released in version 0.0.20 or higher.

In general, for similar reports please also let me know the JupyterHub configuration, and maybe some earlier logs too. It would be good to understand if it is 100% repeatable, or is just an intermittent error.

I'll close this issue for now. Anyone else should please open a new one with any similar reports.
