### ISSUE TITLE
No module named 'cdsdashboards'

### ISSUE THREAD

**Issue by zys2017** [ideonate/cdsdashboards#90]
Hi,
My Dockerfile is from ideonate/cdsdashboards-jupyter-k8s-hub:1.1.3-0.6.0, but the hub is CrashLoopBackOff:
![image](https://user-images.githubusercontent.com/19464887/145335502-7c538ea7-9756-4654-b7c2-1055501dadac.png)
and logs is:
```
Loading /usr/local/etc/jupyterhub/secret/values.yaml
No config at /usr/local/etc/jupyterhub/existing-secret/values.yaml
Loading extra config: cds-handlers
[E 2021-12-09 03:39:46.043 JupyterHub app:2718]
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/app.py", line 2715, in launch_instance_async
        await self.initialize(argv)
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/app.py", line 2238, in initialize
        self.load_config_file(self.config_file)
      File "<decorator-gen-5>", line 2, in load_config_file
      File "/usr/local/lib/python3.6/dist-packages/traitlets/config/application.py", line 87, in catch_config_error
        return method(app, *args, **kwargs)
      File "/usr/local/lib/python3.6/dist-packages/traitlets/config/application.py", line 602, in load_config_file
        raise_config_file_errors=self.raise_config_file_errors,
      File "/usr/local/lib/python3.6/dist-packages/traitlets/config/application.py", line 563, in _load_config_files
        config = loader.load_config()
      File "/usr/local/lib/python3.6/dist-packages/traitlets/config/loader.py", line 457, in load_config
        self._read_file_as_dict()
      File "/usr/local/lib/python3.6/dist-packages/traitlets/config/loader.py", line 489, in _read_file_as_dict
        py3compat.execfile(conf_filename, namespace)
      File "/usr/local/lib/python3.6/dist-packages/ipython_genutils/py3compat.py", line 198, in execfile
        exec(compiler(f.read(), fname, 'exec'), glob, loc)
      File "/usr/local/etc/jupyterhub/jupyterhub_config.py", line 446, in <module>
        exec(config_py)
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'cdsdashboards'
```

**Comment by danlester** [comment]
I haven't had a chance to try ideonate/cdsdashboards-jupyter-k8s-hub:1.1.3-0.6.0 within a Z2JH setting but it does seem to have `cdsdashboards` installed correctly within Python.

My guess is that somehow the hub image isn't being set correctly. I think we'd need to see more of your z2jh config to explore further.

You could also check the hub pod to be sure it's pulling the correct image for the container.

**Comment by raybellwaves** [comment]
Recently got something similar with tljh using a plugin (https://github.com/raybellwaves/tljh-plugin/blob/main/tljh_plugin.py)

**Comment by danlester** [comment]
Closing due to inactivity automatically.
